{% set version = "0.5.1" %}

package:
  name: aha
  version: {{ version }}

source:
  url: https://github.com/theZiz/aha/archive/{{ version }}.tar.gz
  sha256: 6aea13487f6b5c3e453a447a67345f8095282f5acd97344466816b05ebd0b3b1

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]

test:
  commands:
    - aha -h

about:
  home: https://github.com/theZiz/aha
  license: MPL-1.1
  license_file: LICENSE.MPL1.1
  summary: Converts ANSI escape sequences of a unix terminal to HTML code.
  description: |
    Converts ANSI escape sequences of a unix terminal to HTML code.
  doc_url: https://github.com/theZiz/aha
  dev_url: https://github.com/theZiz/aha

extra:
  recipe-maintainers:
    - bsipos
